/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Ais: () => import('#controllers/ais_controller'),
  Auth: () => import('#controllers/auth_controller'),
  ProductSalls: () => import('#controllers/product_salls_controller'),
  Profile: () => import('#controllers/profile_controller'),
  SellingAccounts: () => import('#controllers/selling_accounts_controller'),
}
