/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CropListingSchema extends BaseModel {
  static $columns = ['contactNumber', 'createdAt', 'cropName', 'description', 'harvestDate', 'id', 'images', 'isActive', 'isSalled', 'market', 'pricePerUnit', 'sellingAccountId', 'unit', 'updatedAt', 'userId', 'variety'] as const
  $columns = CropListingSchema.$columns
  @column()
  declare contactNumber: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare cropName: string
  @column()
  declare description: string | null
  @column.date()
  declare harvestDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare images: any | null
  @column()
  declare isActive: boolean | null
  @column()
  declare isSalled: boolean | null
  @column()
  declare market: string
  @column()
  declare pricePerUnit: string | null
  @column()
  declare sellingAccountId: number | null
  @column()
  declare unit: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare variety: string | null
}

export class SellingAccountSchema extends BaseModel {
  static $columns = ['aadhaarNumber', 'aadhaarVerified', 'createdAt', 'cropSeason', 'dateOfBirth', 'district', 'expectedYieldUnit', 'expectedYieldValue', 'farmingType', 'gender', 'id', 'mobileNumber', 'mobileVerified', 'photoUrl', 'pincode', 'primaryCrops', 'sellingAccountName', 'shortAddress', 'soilType', 'state', 'surveyNumber', 'taluka', 'updatedAt', 'userId', 'village'] as const
  $columns = SellingAccountSchema.$columns
  @column()
  declare aadhaarNumber: string
  @column()
  declare aadhaarVerified: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare cropSeason: string | null
  @column.date()
  declare dateOfBirth: DateTime | null
  @column()
  declare district: string | null
  @column()
  declare expectedYieldUnit: string | null
  @column()
  declare expectedYieldValue: string | null
  @column()
  declare farmingType: string | null
  @column()
  declare gender: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mobileNumber: string
  @column()
  declare mobileVerified: boolean
  @column()
  declare photoUrl: string | null
  @column()
  declare pincode: string | null
  @column()
  declare primaryCrops: any | null
  @column()
  declare sellingAccountName: string
  @column()
  declare shortAddress: string
  @column()
  declare soilType: string | null
  @column()
  declare state: string | null
  @column()
  declare surveyNumber: string | null
  @column()
  declare taluka: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare village: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'emailVerificationToken', 'fullName', 'id', 'isEmailVerified', 'password', 'sellingAccountId', 'type', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare emailVerificationToken: string | null
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isEmailVerified: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare sellingAccountId: number | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}
